// Generated by view binder compiler. Do not edit!
package linda.ayu.myapplication1.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager2.widget.ViewPager2;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import linda.ayu.myapplication1.R;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final CardView Bayi;

  @NonNull
  public final CardView Kesehatan;

  @NonNull
  public final CardView Makananminuman;

  @NonNull
  public final CardView Rumah;

  @NonNull
  public final ViewPager2 ViewPager;

  @NonNull
  public final LinearLayout dotsIndicator;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView, @NonNull CardView Bayi,
      @NonNull CardView Kesehatan, @NonNull CardView Makananminuman, @NonNull CardView Rumah,
      @NonNull ViewPager2 ViewPager, @NonNull LinearLayout dotsIndicator) {
    this.rootView = rootView;
    this.Bayi = Bayi;
    this.Kesehatan = Kesehatan;
    this.Makananminuman = Makananminuman;
    this.Rumah = Rumah;
    this.ViewPager = ViewPager;
    this.dotsIndicator = dotsIndicator;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Bayi;
      CardView Bayi = ViewBindings.findChildViewById(rootView, id);
      if (Bayi == null) {
        break missingId;
      }

      id = R.id.Kesehatan;
      CardView Kesehatan = ViewBindings.findChildViewById(rootView, id);
      if (Kesehatan == null) {
        break missingId;
      }

      id = R.id.Makananminuman;
      CardView Makananminuman = ViewBindings.findChildViewById(rootView, id);
      if (Makananminuman == null) {
        break missingId;
      }

      id = R.id.Rumah;
      CardView Rumah = ViewBindings.findChildViewById(rootView, id);
      if (Rumah == null) {
        break missingId;
      }

      id = R.id.View_pager;
      ViewPager2 ViewPager = ViewBindings.findChildViewById(rootView, id);
      if (ViewPager == null) {
        break missingId;
      }

      id = R.id.dots_indicator;
      LinearLayout dotsIndicator = ViewBindings.findChildViewById(rootView, id);
      if (dotsIndicator == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, Bayi, Kesehatan, Makananminuman,
          Rumah, ViewPager, dotsIndicator);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
